# """
# Django settings for core project.

# Generated by 'django-admin startproject' using Django 5.2.6.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.2/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.2/ref/settings/
# """

# from pathlib import Path
# from dotenv import load_dotenv
# import os


# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
# load_dotenv(BASE_DIR / ".env")

# SECRET_KEY = os.getenv("SECRET_KEY", "changeme-in-prod")
# DEBUG = os.getenv("DEBUG", "False") == "True"

# ALLOWED_HOSTS = [
#     "localhost",
#     "127.0.0.1",
#     "testserver",
#     "dibiyes.cluster024.hosting.ovh.net",
# ]

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": os.getenv("DB_NAME", "christland"),
#         "USER": os.getenv("DB_USER", "postgres"),
#         "PASSWORD": os.getenv("DB_PASSWORD", ""),
#         "HOST": os.getenv("DB_HOST", "localhost"),
#         "PORT": os.getenv("DB_PORT", "5432"),
#     }
# }

# CONTENT_SECURITY_POLICY = {
#     "DIRECTIVES": {
#         "default-src": ("'self'",),
#         "script-src": ("'self'", "'unsafe-inline'"),
#         "style-src": ("'self'", "https://fonts.googleapis.com", "'unsafe-inline'"),
#         "img-src": ("'self'", "data:",),
#         "connect-src": ("'self'",),
#         "font-src": ("'self'", "https://fonts.gstatic.com"),
#     }
# }

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'corsheaders.middleware.CorsMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
#     'csp.middleware.CSPMiddleware',
# ]

# ROOT_URLCONF = 'core.urls'



# INSTALLED_APPS = [
#     # Apps Django de base
#     "django.contrib.admin",
#     "django.contrib.auth",
#     "django.contrib.contenttypes",
#     "django.contrib.sessions",
#     "django.contrib.messages",
#     "django.contrib.staticfiles",

#     # Apps tierces
#     "rest_framework",
#     "corsheaders",
#     "csp",

#     # Ton app principale
#     "christland",
# ]



# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'core.wsgi.application'


# # Langues cibles pour les traductions
# I18N_TARGET_LANGS = ["en"]

# # Active / désactive la traduction automatique à chaque save
# AUTO_BUILD_TRANSLATIONS = True  # True en dev si tu veux, False en prod si tu préfères

# # import environ, os
# # env = environ.Env(DEBUG=(bool, False))
# # environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# # DEBUG = env("DEBUG")
# # SECRET_KEY = env("SECRET_KEY", default="unsafe-secret")
# # ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["127.0.0.1", "localhost"])

# # # DB
# # if env("DB_ENGINE") == "postgres":
# #     DATABASES = {
# #         "default": {
# #             "ENGINE": "django.db.backends.postgresql_psycopg2",
# #             "NAME": env("DB_NAME"),
# #             "USER": env("DB_USER"),
# #             "PASSWORD": env("DB_PASSWORD"),
# #             "HOST": env("DB_HOST", default="127.0.0.1"),
# #             "PORT": env("DB_PORT", default="5432"),
# #         }
# #     }
# # else:
# #     DATABASES = {"default": {"ENGINE": "django.db.backends.sqlite3", "NAME": BASE_DIR / "db.sqlite3"}}



# # Database
# # https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.sqlite3',
# #         'NAME': BASE_DIR / 'db.sqlite3',
# #     }
# # }


# MEDIA_URL = "/media/"
# MEDIA_ROOT = BASE_DIR / "media"

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": os.getenv("DB_NAME", "christland"),
#         "USER": os.getenv("DB_USER", "postgres"),
#         "PASSWORD": os.getenv("DB_PASSWORD", ""),
#         "HOST": os.getenv("DB_HOST", "localhost"),
#         "PORT": os.getenv("DB_PORT", "5432"),
#     }
# }



# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",   # dev React
#     "https://dibiyes.cluster024.hosting.ovh.net",  # prod OVH sans domaine
# ]

# CSRF_TRUSTED_ORIGINS = [
#     "http://localhost:5173",
#     "https://dibiyes.cluster024.hosting.ovh.net",
# ]


# CORS_ALLOW_HEADERS = [
#     "accept",
#     "accept-encoding",
#     "authorization",
#     "content-type",
#     "dnt",
#     "origin",
#     "user-agent",
#     "x-csrftoken",
#     "x-requested-with",
#     "x-lang",  # ← INDISPENSABLE POUR LA TRADUCTION
# ]


# # Password validation
# # https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True


# # # # settings.py
# # # DEFAULT_FROM_EMAIL = "nzogue.dibiye@gmail.com"
# # # CONTACT_RECIPIENTS = ["nzogue.dibiye@gmail.com"]  # liste de destinataires
# # # EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# # # # configure aussi ton SMTP (HOST, PORT, USER, PASSWORD, TLS/SSL) selon ton provider

# # # Qui reçoit les messages
# # CONTACT_INBOX = "rachelnzogue9@gmail.com"

# # # SMTP technique (ne change pas selon l’utilisateur)
# # EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# # EMAIL_HOST = "smtp.gmail.com"
# # EMAIL_PORT = 587
# # EMAIL_USE_TLS = True
# # EMAIL_HOST_USER = "rachelnzogue9@gmail.com"              # ton compte émetteur
# # EMAIL_HOST_PASSWORD = "nqfgoakcuiwvrwbz"   # mot de passe d’application Gmail
# # DEFAULT_FROM_EMAIL = EMAIL_HOST_USER                      # expéditeur “technique”
# # EMAIL_TIMEOUT = 20


# # Qui reçoit les messages
# CONTACT_INBOX = "info@christland.tech"

# # Backend d'envoi
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

# # 🔐 SMTP OVH
# EMAIL_HOST = "ssl0.ovh.net"      # serveur SMTP OVH
# EMAIL_PORT = 587                 # port TLS
# EMAIL_USE_TLS = True             # on active TLS

# EMAIL_HOST_USER = "info@christland.tech"   # ton adresse mail OVH complète
# EMAIL_HOST_PASSWORD = "TON_MOT_DE_PASSE_ICI"   # mot de passe de la boîte mail

# # Adresse qui apparaîtra comme expéditeur
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# EMAIL_TIMEOUT = 20




# load_dotenv(BASE_DIR / ".env")
# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = 'static/'

# # Default primary key field type
# # https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST_FRAMEWORK = {
#     "DEFAULT_RENDERER_CLASSES": ["rest_framework.renderers.JSONRenderer"],
#     "DEFAULT_PARSER_CLASSES": ["rest_framework.parsers.JSONParser"],
#     "DEFAULT_AUTHENTICATION_CLASSES": (
#         "christland.auth_jwt.JWTAuthentication",  # ← ton auth
#     ),
# }

# CACHES = {
#     "default": {
#         "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
#         "LOCATION": "christland-locmem-cache",
#     }
# }


# # LIBRETRANSLATE_URL = "https://libretranslate.com"



"""
Django settings for core project.

- Utilise PostgreSQL via les variables d'environnement (.env)
- Local :
    DB_NAME = christland
    DB_USER = postgres
    DB_PASSWORD = Admin1234
    DB_HOST = localhost
    DB_PORT = 5432
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# === Chemins ===
BASE_DIR = Path(__file__).resolve().parent.parent

# Charge le fichier .env situé dans backend/.env
load_dotenv(BASE_DIR / ".env")

# === Sécurité / Debug ===
SECRET_KEY = os.getenv("SECRET_KEY", "dev-insecure-key")
DEBUG = os.getenv("DEBUG", "True") == "True"

ALLOWED_HOSTS = os.getenv(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1,christlandtech.onrender.com",
).split(",")

# === Base de données (local ou Render selon .env) ===
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}

# === Fichiers statiques & médias ===
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# === APPS ===
INSTALLED_APPS = [
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Tiers
    "rest_framework",
    "corsheaders",
    "csp",

    # App principale
    "christland",
]

# === MIDDLEWARE ===
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "csp.middleware.CSPMiddleware",
]

ROOT_URLCONF = "core.urls"

# === Templates ===
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"

# === Content Security Policy (CSP) ===
CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        "default-src": ("'self'",),
        "script-src": ("'self'", "'unsafe-inline'"),
        "style-src": ("'self'", "https://fonts.googleapis.com", "'unsafe-inline'"),
        "img-src": ("'self'", "data:",),
        "connect-src": ("'self'",),
        "font-src": ("'self'", "https://fonts.gstatic.com"),
    }
}

# === Traduction interne ===
I18N_TARGET_LANGS = ["en"]
AUTO_BUILD_TRANSLATIONS = True

# === CORS / CSRF (LOCAL + PROD) ===

# En local (DEBUG=True) : on ouvre pour éviter les blocages pendant le dev
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    # En prod : on limite aux origines connues
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:5173",                      # si tu gardes un front dev
        # "https://dibiyes.cluster024.hosting.ovh.net", # OVH
        "https://christlandtech.onrender.com",        # Render backend
        "https://christlandtech-frontend.onrender.com",
    ]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    # "https://dibiyes.cluster024.hosting.ovh.net",
    "https://christlandtech.onrender.com",
    "https://christlandtech-frontend.onrender.com",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "x-lang",  # pour ta logique de traduction
]

# === Validation mot de passe ===
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# === Internationalisation ===
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# === Email (OVH – à passer en variables d'env plus tard) ===
CONTACT_INBOX = "info@christland.tech"

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "ssl0.ovh.net"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "info@christland.tech"
EMAIL_HOST_PASSWORD = "TON_MOT_DE_PASSE_ICI"  # à mettre dans .env plus tard
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_TIMEOUT = 20

# === Static (déjà défini plus haut, on garde) ===
STATIC_URL = "static/"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# === DRF ===
REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": ["rest_framework.renderers.JSONRenderer"],
    "DEFAULT_PARSER_CLASSES": ["rest_framework.parsers.JSONParser"],
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "christland.auth_jwt.JWTAuthentication",
    ),
}

# === Cache ===
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "christland-locmem-cache",
    }
}

# Si tu veux un jour :
# LIBRETRANSLATE_URL = os.getenv("LIBRETRANSLATE_URL", "https://libretranslate.com")

# Si tu veux réactiver plus tard :
# LIBRETRANSLATE_URL = "https://libretranslate.com"
