# Generated by Django 5.1.2 on 2025-09-29 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('image_url', models.CharField(blank=True, max_length=255)),
                ('est_actif', models.BooleanField(default=False)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Commandes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(blank=True, max_length=255)),
                ('statut_paiement', models.CharField(blank=True, max_length=255)),
                ('statut_livraison', models.CharField(blank=True, max_length=255)),
                ('sous_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_remise', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_livraison', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_taxes', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_general', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('cree_le', models.DateTimeField(blank=True, null=True)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('modifie_le', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'commandes',
            },
        ),
        migrations.CreateModel(
            name='Couleurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255)),
                ('code_hex', models.CharField(blank=True, max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255)),
                ('est_active', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(blank=True, null=True)),
                ('modifie_le', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'couleurs',
            },
        ),
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, max_length=255)),
                ('premier_achat_uniquement', models.BooleanField(default=False)),
                ('canal', models.CharField(blank=True, max_length=255)),
                ('valeur', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('montant_minimal', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('actif', models.BooleanField(default=False)),
                ('debut', models.DateTimeField(blank=True, null=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(blank=True, null=True)),
                ('cumulable', models.BooleanField(default=False)),
                ('modifie_le', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coupons',
            },
        ),
        migrations.CreateModel(
            name='Entrepots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255)),
                ('adresse_json', models.CharField(blank=True, max_length=255)),
                ('gps_lat_gps_lon', models.CharField(blank=True, max_length=255)),
                ('est_actif', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'entrepots',
            },
        ),
        migrations.CreateModel(
            name='FavorisClasseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255)),
                ('cree_le', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'favoris_classeur',
            },
        ),
        migrations.CreateModel(
            name='Livreurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, max_length=255)),
                ('vehicule', models.CharField(blank=True, max_length=255)),
                ('zone', models.CharField(blank=True, max_length=255)),
                ('disponibilite', models.CharField(blank=True, max_length=255)),
                ('immatriculation', models.CharField(blank=True, max_length=255)),
                ('cree_le', models.DateTimeField(blank=True, null=True)),
                ('modifie_le', models.DateTimeField(blank=True, null=True)),
                ('actif', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'livreurs',
            },
        ),
        migrations.CreateModel(
            name='Marques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255)),
                ('logo_url', models.CharField(blank=True, max_length=255)),
                ('site_web_url', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('pays_origine', models.CharField(blank=True, max_length=255)),
                ('cree_le', models.DateTimeField(blank=True, null=True)),
                ('est_active', models.BooleanField(blank=True, default=None, null=True)),
                ('modifie_le', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'marques',
            },
        ),
        migrations.CreateModel(
            name='Representants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=255)),
                ('actif', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'representants',
            },
        ),
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=255)),
                ('mot_de_passe_hash', models.CharField(blank=True, max_length=255)),
                ('prenom', models.CharField(blank=True, max_length=255)),
                ('nom', models.CharField(blank=True, max_length=255)),
                ('actif', models.BooleanField(default=False)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('cree_le', models.DateTimeField(blank=True, null=True)),
                ('modifie_le', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='ArticlesBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255)),
                ('extrait', models.CharField(blank=True, max_length=255)),
                ('contenu', models.CharField(blank=True, max_length=255)),
                ('image_couverture', models.CharField(blank=True, max_length=255)),
                ('publie_le', models.DateTimeField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(blank=True, null=True)),
                ('modifie_le', models.DateTimeField(blank=True, null=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='christland.categories')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='christland.utilisateurs')),
            ],
            options={
                'db_table': 'articles_blog',
            },
        ),
        migrations.CreateModel(
            name='AdressesCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=255)),
                ('nom_complet', models.CharField(blank=True, max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('ligne1', models.CharField(blank=True, max_length=255)),
                ('ligne2', models.CharField(blank=True, max_length=255)),
                ('ville', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('code_postal', models.CharField(blank=True, max_length=255)),
                ('pays', models.CharField(blank=True, max_length=255)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to='christland.commandes')),
            ],
            options={
                'db_table': 'adresses_commande',
            },
        ),
        migrations.CreateModel(
            name='Expeditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(blank=True, max_length=255)),
                ('numero_suivi', models.CharField(blank=True, max_length=255)),
                ('preuve_signature_url', models.CharField(blank=True, max_length=255)),
                ('preuve_photo_url', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(blank=True, max_length=255)),
                ('Expedier_le', models.DateTimeField(blank=True, null=True)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expeditions', to='christland.commandes')),
                ('livreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expeditions', to='christland.livreurs')),
            ],
            options={
                'db_table': 'expeditions',
            },
        ),
        migrations.CreateModel(
            name='Paiements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fournisseur', models.CharField(blank=True, max_length=255)),
                ('transaction_externe_id', models.CharField(blank=True, max_length=255)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('statut', models.CharField(blank=True, max_length=255)),
                ('pays', models.CharField(blank=True, max_length=255)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='christland.commandes')),
            ],
            options={
                'db_table': 'paiements',
            },
        ),
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255)),
                ('description_courte', models.CharField(blank=True, max_length=255)),
                ('description_long', models.CharField(blank=True, max_length=255)),
                ('garantie_mois', models.IntegerField(blank=True, null=True)),
                ('poids_grammes', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('est_actif', models.BooleanField(default=False)),
                ('visible', models.IntegerField(blank=True, null=True)),
                ('prix_reference_avant', models.IntegerField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(blank=True, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=255)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='christland.categories')),
                ('marque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='christland.marques')),
            ],
            options={
                'db_table': 'produits',
            },
        ),
        migrations.CreateModel(
            name='ImagesProduits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('principale', models.BooleanField(default=False)),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='christland.produits')),
            ],
            options={
                'db_table': 'images_produits',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='BandeauxMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=255)),
                ('image_url', models.CharField(blank=True, max_length=255)),
                ('lien_url', models.CharField(blank=True, max_length=255)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('actif', models.BooleanField(default=False)),
                ('debut', models.DateTimeField(blank=True, null=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bandeaux', to='christland.categories')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bandeaux', to='christland.coupons')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bandeaux', to='christland.produits')),
            ],
            options={
                'db_table': 'bandeaux_marketing',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Remboursements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(blank=True, max_length=255)),
                ('paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remboursements', to='christland.paiements')),
            ],
            options={
                'db_table': 'remboursements',
            },
        ),
        migrations.CreateModel(
            name='Paniers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('cree_le', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paniers', to='christland.utilisateurs')),
            ],
            options={
                'db_table': 'paniers',
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(blank=True, max_length=255)),
                ('modele', models.CharField(blank=True, max_length=255)),
                ('payload_json', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(blank=True, max_length=255)),
                ('cree_le', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='christland.utilisateurs')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='MessagesContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=255)),
                ('canal_prefere', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(blank=True, max_length=255)),
                ('sujet', models.CharField(blank=True, max_length=255)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('cree_le', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_contact', to='christland.utilisateurs')),
            ],
            options={
                'db_table': 'messages_contact',
            },
        ),
        migrations.CreateModel(
            name='Favoris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255)),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='christland.favorisclasseur')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='christland.utilisateurs')),
            ],
            options={
                'db_table': 'favoris',
            },
        ),
        migrations.CreateModel(
            name='EvenementsAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evenement', models.CharField(blank=True, max_length=255)),
                ('date_evenement', models.DateTimeField(blank=True, null=True)),
                ('page_url', models.CharField(blank=True, max_length=255)),
                ('utm_source', models.CharField(blank=True, max_length=255)),
                ('appareil', models.CharField(blank=True, max_length=255)),
                ('utm_campaign', models.CharField(blank=True, max_length=255)),
                ('pays', models.CharField(blank=True, max_length=255)),
                ('ip_client', models.CharField(blank=True, max_length=255)),
                ('ville', models.CharField(blank=True, max_length=255)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_analytics', to='christland.utilisateurs')),
            ],
            options={
                'db_table': 'evenements_analytics',
            },
        ),
        migrations.CreateModel(
            name='CouponsUtilisations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilise_le', models.DateTimeField(blank=True, null=True)),
                ('commission_montant', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('montant_remise', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('commission_statut', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons_utilises', to='christland.commandes')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisations', to='christland.coupons')),
                ('representant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons_utilises', to='christland.representants')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons_utilises', to='christland.utilisateurs')),
            ],
            options={
                'db_table': 'coupons_utilisations',
            },
        ),
        migrations.CreateModel(
            name='CommentairesBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(blank=True, max_length=255)),
                ('valide', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(blank=True, null=True)),
                ('approuve_le', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='christland.articlesblog')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commentaires_blog', to='christland.utilisateurs')),
            ],
            options={
                'db_table': 'commentaires_blog',
            },
        ),
        migrations.AddField(
            model_name='commandes',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='christland.utilisateurs'),
        ),
        migrations.CreateModel(
            name='AvisProduits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(blank=True, null=True)),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='christland.produits')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avis', to='christland.utilisateurs')),
            ],
            options={
                'db_table': 'avis_produits',
            },
        ),
        migrations.CreateModel(
            name='Adresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=255)),
                ('nom_complet', models.CharField(blank=True, max_length=255)),
                ('ligne1', models.CharField(blank=True, max_length=255)),
                ('ligne2', models.CharField(blank=True, max_length=255)),
                ('ville', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('code_postal', models.CharField(blank=True, max_length=255)),
                ('pays', models.CharField(blank=True, max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=255)),
                ('cree_le', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adresses', to='christland.utilisateurs')),
            ],
            options={
                'db_table': 'adresses',
            },
        ),
        migrations.CreateModel(
            name='VariantesProduits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=255)),
                ('code_barres', models.CharField(blank=True, max_length=255)),
                ('nom', models.CharField(blank=True, max_length=255)),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('prix_promo', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('poids_grammes', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('cree_le', models.DateTimeField(blank=True, null=True)),
                ('prix_achat', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('est_actif', models.BooleanField(default=False)),
                ('couleur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variantes', to='christland.couleurs')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='christland.produits')),
            ],
            options={
                'db_table': 'variantes_produits',
            },
        ),
        migrations.CreateModel(
            name='MouvementsStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=255)),
                ('quantite', models.IntegerField(blank=True, null=True)),
                ('raison', models.DateTimeField(blank=True, null=True)),
                ('gps_lat_gps_lon', models.CharField(blank=True, max_length=255)),
                ('entrepot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='christland.entrepots')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='christland.variantesproduits')),
            ],
            options={
                'db_table': 'mouvements_stock',
            },
        ),
        migrations.CreateModel(
            name='LignesPanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(blank=True, null=True)),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('panier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='christland.paniers')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_panier', to='christland.variantesproduits')),
            ],
            options={
                'db_table': 'lignes_panier',
            },
        ),
        migrations.CreateModel(
            name='LignesCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(blank=True, null=True)),
                ('prix_unitaire_lic', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_ligne', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('nom_snapshot_lic', models.CharField(blank=True, max_length=255)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='christland.commandes')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commande', to='christland.variantesproduits')),
            ],
            options={
                'db_table': 'lignes_commande',
            },
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_disponible', models.IntegerField()),
                ('quantite_reservee', models.IntegerField(default=0)),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='christland.entrepots')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='christland.variantesproduits')),
            ],
            options={
                'db_table': 'stocks',
                'unique_together': {('variante', 'entrepot')},
            },
        ),
    ]
