# Generated by Django 5.1.2 on 2025-09-25 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleBlog',
            fields=[
                ('id', models.BigAutoField(db_column='article_id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='titre_ar', max_length=250)),
                ('slug', models.SlugField(db_column='slug_ar', max_length=260, unique=True)),
                ('excerpt', models.CharField(blank=True, db_column='extrait_ar', max_length=400)),
                ('content', models.TextField(db_column='contenu_ar')),
                ('cover_url', models.URLField(blank=True, db_column='image_couverture_ar')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='cree_le_ar')),
            ],
            options={
                'db_table': 'articles_blog',
            },
        ),
        migrations.CreateModel(
            name='BandeauMarketing',
            fields=[
                ('id', models.BigAutoField(db_column='bandeau_id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='titre_ban', max_length=200)),
                ('image_url', models.URLField(db_column='image_url_ban')),
                ('link_url', models.URLField(blank=True, db_column='lien_url_ban')),
                ('position', models.CharField(db_column='position_ban', max_length=50)),
                ('is_active', models.BooleanField(db_column='est_actif_ban', default=True)),
            ],
            options={
                'db_table': 'bandeaux_marketing',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(db_column='commande_id', primary_key=True, serialize=False)),
                ('number', models.CharField(db_column='numero_com', max_length=30, unique=True)),
                ('status', models.CharField(db_column='statut_com', default='EN_COURS', max_length=30)),
                ('payment_status', models.CharField(db_column='statut_paiement_com', default='EN_ATTENTE', max_length=30)),
                ('total', models.DecimalField(db_column='total_ttc', decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='cree_le_com')),
            ],
            options={
                'db_table': 'commandes',
            },
        ),
        migrations.CreateModel(
            name='Couleur',
            fields=[
                ('id', models.BigAutoField(db_column='couleur_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nom_cou', max_length=100)),
                ('hex_code', models.CharField(db_column='code_hex_cou', max_length=7)),
                ('slug', models.SlugField(db_column='slug_cou', max_length=120, unique=True)),
                ('is_active', models.BooleanField(db_column='est_active_cou', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='cree_le_cou')),
            ],
            options={
                'db_table': 'couleurs',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(db_column='coupon_id', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='code_cou', max_length=40, unique=True)),
                ('kind', models.CharField(db_column='type_cou', max_length=20)),
                ('value', models.DecimalField(db_column='valeur_cou', decimal_places=2, max_digits=10)),
                ('first_order_only', models.BooleanField(db_column='premier_achat_uniquement_cou', default=False)),
                ('is_active', models.BooleanField(db_column='actif_cou', default=True)),
            ],
            options={
                'db_table': 'coupons',
            },
        ),
        migrations.CreateModel(
            name='Entrepot',
            fields=[
                ('id', models.BigAutoField(db_column='entrepot_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nom_en', max_length=200)),
                ('address', models.JSONField(db_column='adresse_json_en')),
                ('lat', models.DecimalField(db_column='gps_lat', decimal_places=7, max_digits=10)),
                ('lon', models.DecimalField(db_column='gps_lon', decimal_places=7, max_digits=10)),
            ],
            options={
                'db_table': 'entrepots',
            },
        ),
        migrations.CreateModel(
            name='EvenementAnalytics',
            fields=[
                ('id', models.BigAutoField(db_column='evenement_id', primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_column='type_evenement', max_length=60)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_column='date_evenement')),
                ('page_url', models.URLField(db_column='page_url')),
                ('utm_source', models.CharField(blank=True, db_column='utm_source', max_length=120)),
                ('utm_campaign', models.CharField(blank=True, db_column='utm_campaign', max_length=120)),
            ],
            options={
                'db_table': 'evenements_analytics',
            },
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(db_column='marque_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nom_mar', max_length=200)),
                ('slug', models.SlugField(db_column='slug_mar', max_length=220, unique=True)),
                ('logo_url', models.URLField(blank=True, db_column='logo_url_mar')),
                ('website', models.URLField(blank=True, db_column='site_web_url_mar')),
                ('country', models.CharField(blank=True, db_column='pays_origine_mar', max_length=120)),
            ],
            options={
                'db_table': 'marques',
            },
        ),
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(db_column='message_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nom_me', max_length=200)),
                ('email', models.EmailField(db_column='email_me', max_length=255)),
                ('phone', models.CharField(blank=True, db_column='telephone_me', max_length=30)),
                ('subject', models.CharField(blank=True, db_column='sujet_me', max_length=255)),
                ('content', models.TextField(db_column='contenu_me')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='cree_le_me')),
            ],
            options={
                'db_table': 'messages_contact',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(db_column='utilisateur_id', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_column='email_ut', max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, db_column='telephone_ut', max_length=30)),
                ('password_hash', models.CharField(db_column='mot_de_passe_hash', max_length=255)),
                ('first_name', models.CharField(blank=True, db_column='nom_ut', max_length=150)),
                ('last_name', models.CharField(blank=True, db_column='prenom_ut', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='cree_le_ut')),
            ],
            options={
                'db_table': 'utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(db_column='categorie_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nom_ca', max_length=200)),
                ('slug', models.SlugField(db_column='slug_ca', max_length=220, unique=True)),
                ('description', models.TextField(blank=True, db_column='description_ca')),
                ('image_url', models.URLField(blank=True, db_column='image_url_ca')),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='christland.categorie')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='AdresseCommande',
            fields=[
                ('id', models.BigAutoField(db_column='adresse_id', primary_key=True, serialize=False)),
                ('type', models.CharField(db_column='type_ac', max_length=20)),
                ('full_name', models.CharField(db_column='nom_complet_ac', max_length=200)),
                ('phone', models.CharField(db_column='telephone_ac', max_length=30)),
                ('data', models.JSONField(db_column='adresse_json_ac')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='christland.commande')),
            ],
            options={
                'db_table': 'adresses_commande',
            },
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(db_column='expedition_id', primary_key=True, serialize=False)),
                ('mode', models.CharField(db_column='mode_ex', max_length=50)),
                ('tracking', models.CharField(blank=True, db_column='tracking_ex', max_length=120)),
                ('signature_url', models.URLField(blank=True, db_column='signature_url_ex')),
                ('proof_photo_url', models.URLField(blank=True, db_column='preuve_photo_url_ex')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='christland.commande')),
            ],
            options={
                'db_table': 'expeditions',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(db_column='paiement_id_pai', primary_key=True, serialize=False)),
                ('provider', models.CharField(db_column='fournisseur_pai', max_length=60)),
                ('external_id', models.CharField(db_column='transaction_externe_id_pai', max_length=120)),
                ('amount', models.DecimalField(db_column='montant_pai', decimal_places=2, max_digits=12)),
                ('status', models.CharField(db_column='statut_pai', default='EN_ATTENTE', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='cree_le_pai')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='christland.commande')),
            ],
            options={
                'db_table': 'paiements',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(db_column='produit_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nom_pr', max_length=250)),
                ('slug', models.SlugField(db_column='slug_pr', max_length=260, unique=True)),
                ('short_desc', models.CharField(blank=True, db_column='description_courte_pr', max_length=500)),
                ('description', models.TextField(blank=True, db_column='description_pr')),
                ('is_active', models.BooleanField(db_column='actif_pr', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='cree_le_pr')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='christland.categorie')),
                ('marque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='christland.marque')),
            ],
            options={
                'db_table': 'produits',
            },
        ),
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.BigAutoField(db_column='remboursement_id', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(db_column='montant_rem', decimal_places=2, max_digits=12)),
                ('reason', models.TextField(blank=True, db_column='motif_rem')),
                ('status', models.CharField(db_column='statut_rem', default='EN_ATTENTE', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='cree_le_rem')),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='christland.paiement')),
            ],
            options={
                'db_table': 'remboursements',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(db_column='stock_id', primary_key=True, serialize=False)),
                ('qty_available', models.IntegerField(db_column='quantite_disponible_st', default=0)),
                ('qty_reserved', models.IntegerField(db_column='quantite_reservee_st', default=0)),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='christland.entrepot')),
            ],
            options={
                'db_table': 'stocks',
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(db_column='mouvement_id', primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('ENTREE', 'ENTREE'), ('DEBIT', 'DEBIT')], db_column='type_mou', max_length=10)),
                ('qty', models.IntegerField(db_column='quantite_mou')),
                ('reason', models.CharField(blank=True, db_column='raison_mou', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='cree_le_mou')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='christland.stock')),
            ],
            options={
                'db_table': 'mouvements_stock',
            },
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(db_column='panier_id', primary_key=True, serialize=False)),
                ('total', models.DecimalField(db_column='montant_p', decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='cree_le_p')),
                ('session_id', models.CharField(blank=True, db_column='session_id_p', max_length=100)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='christland.utilisateur')),
            ],
            options={
                'db_table': 'paniers',
            },
        ),
        migrations.CreateModel(
            name='Favoris',
            fields=[
                ('id', models.BigAutoField(db_column='favoris_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nom_fa', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='cree_le_fa')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='christland.utilisateur')),
            ],
            options={
                'db_table': 'favoris',
            },
        ),
        migrations.CreateModel(
            name='CommentaireBlog',
            fields=[
                ('id', models.BigAutoField(db_column='commentaire_id', primary_key=True, serialize=False)),
                ('content', models.TextField(db_column='contenu_com')),
                ('status', models.CharField(db_column='statut_com', default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='cree_le_com')),
                ('approved_at', models.DateTimeField(blank=True, db_column='approuve_le_com', null=True)),
                ('is_valid', models.BooleanField(db_column='est_valide_com', default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='christland.articleblog')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_comments', to='christland.utilisateur')),
            ],
            options={
                'db_table': 'commentaires_blog',
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='christland.utilisateur'),
        ),
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(db_column='adresse_id', primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, db_column='libelle_ad', max_length=200, null=True)),
                ('full_name', models.CharField(blank=True, db_column='nom_complet_ad', max_length=200, null=True)),
                ('line1', models.CharField(blank=True, db_column='ligne1_ad', max_length=200, null=True)),
                ('line2', models.CharField(blank=True, db_column='ligne2_ad', max_length=200, null=True)),
                ('city', models.CharField(blank=True, db_column='ville_ad', max_length=120, null=True)),
                ('region', models.CharField(blank=True, db_column='region_ad', max_length=120, null=True)),
                ('postal_code', models.CharField(blank=True, db_column='code_postal_ad', max_length=20, null=True)),
                ('country', models.CharField(blank=True, db_column='pays_ad', max_length=120, null=True)),
                ('phone', models.CharField(blank=True, db_column='telephone_ad', max_length=30, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='christland.utilisateur')),
            ],
            options={
                'db_table': 'adresses',
            },
        ),
        migrations.CreateModel(
            name='VarianteProduit',
            fields=[
                ('id', models.BigAutoField(db_column='variante_id', primary_key=True, serialize=False)),
                ('sku', models.CharField(db_column='sku_va', max_length=80, unique=True)),
                ('barcode', models.CharField(blank=True, db_column='code_barres_va', max_length=64)),
                ('name', models.CharField(blank=True, db_column='nom_va', max_length=200)),
                ('price', models.DecimalField(db_column='prix_ttc_va', decimal_places=2, max_digits=12)),
                ('weight_g', models.PositiveIntegerField(db_column='poids_grammes_va', default=0)),
                ('is_active', models.BooleanField(db_column='actif_va', default=True)),
                ('couleur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='christland.couleur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='christland.produit')),
            ],
            options={
                'db_table': 'variantes_produits',
            },
        ),
        migrations.AddField(
            model_name='stock',
            name='variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='christland.varianteproduit'),
        ),
        migrations.CreateModel(
            name='LignePanier',
            fields=[
                ('id', models.BigAutoField(db_column='ligne_panier_id', primary_key=True, serialize=False)),
                ('qty', models.PositiveIntegerField(db_column='quantite_pa')),
                ('unit_price', models.DecimalField(db_column='prix_unitaire_pa', decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='cree_le_pa')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='christland.panier')),
                ('variante', models.ForeignKey(db_column='variante_id_pa', on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='christland.varianteproduit')),
            ],
            options={
                'db_table': 'lignes_panier',
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(db_column='ligne_commande_id', primary_key=True, serialize=False)),
                ('name_snapshot', models.CharField(db_column='nom_snapshot_lc', max_length=250)),
                ('unit_price', models.DecimalField(db_column='prix_unitaire_lic', decimal_places=2, max_digits=12)),
                ('qty', models.PositiveIntegerField(db_column='quantite_lic')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='christland.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='christland.produit')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='christland.varianteproduit')),
            ],
            options={
                'db_table': 'lignes_commande',
            },
        ),
        migrations.CreateModel(
            name='ImageProduit',
            fields=[
                ('id', models.BigAutoField(db_column='image_id', primary_key=True, serialize=False)),
                ('url', models.URLField(db_column='url_im_im')),
                ('alt', models.CharField(blank=True, db_column='alt_text_im', max_length=255)),
                ('position', models.IntegerField(db_column='position_im', default=0)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='christland.produit')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='christland.varianteproduit')),
            ],
            options={
                'db_table': 'images_produits',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='CouponUtilisation',
            fields=[
                ('id', models.BigAutoField(db_column='utilisation_id', primary_key=True, serialize=False)),
                ('used_at', models.DateTimeField(auto_now_add=True, db_column='utilise_le_cu')),
                ('discount_amount', models.DecimalField(db_column='montant_remise_cu', decimal_places=2, max_digits=12)),
                ('state', models.CharField(db_column='etat', default='APPLIQUE', max_length=20)),
                ('first_order', models.BooleanField(db_column='premier_achat', default=False)),
                ('commission_amount', models.DecimalField(db_column='commission_montant', decimal_places=2, default=0, max_digits=12)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='christland.commande')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='christland.coupon')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='christland.utilisateur')),
            ],
            options={
                'db_table': 'coupons_utilisations',
                'unique_together': {('coupon', 'commande')},
            },
        ),
        migrations.CreateModel(
            name='AvisProduit',
            fields=[
                ('id', models.BigAutoField(db_column='avis_id', primary_key=True, serialize=False)),
                ('rating', models.DecimalField(db_column='note_re', decimal_places=1, max_digits=3)),
                ('comment', models.TextField(blank=True, db_column='commentaire_re')),
                ('status', models.CharField(db_column='status_re', default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='cree_le_re')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='christland.produit')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='christland.utilisateur')),
            ],
            options={
                'db_table': 'avis_produits',
                'unique_together': {('produit', 'utilisateur')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('entrepot', 'variante')},
        ),
        migrations.CreateModel(
            name='FavorisClasseur',
            fields=[
                ('id', models.BigAutoField(db_column='element_id', primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True, db_column='ajoute_le_fc')),
                ('favoris', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='christland.favoris')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='christland.produit')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='christland.varianteproduit')),
            ],
            options={
                'db_table': 'favoris_classeur',
                'indexes': [models.Index(fields=['favoris', 'produit'], name='favoris_cla_favoris_dc1b38_idx'), models.Index(fields=['favoris', 'variante'], name='favoris_cla_favoris_c446b5_idx')],
            },
        ),
    ]
