# Generated by Django 5.1.2 on 2025-09-25 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('adresse_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(blank=True, max_length=254, null=True)),
                ('nom_complet', models.CharField(blank=True, max_length=254, null=True)),
                ('ligne1', models.CharField(blank=True, max_length=254, null=True)),
                ('ligne2', models.CharField(blank=True, max_length=254, null=True)),
                ('ville', models.CharField(blank=True, max_length=254, null=True)),
                ('region', models.CharField(blank=True, max_length=254, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=254, null=True)),
                ('pays', models.CharField(blank=True, max_length=254, null=True)),
                ('defaut_facturation', models.BooleanField(blank=True, null=True)),
                ('defaut_livraison', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'adresses',
            },
        ),
        migrations.CreateModel(
            name='ArticleBlog',
            fields=[
                ('article_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(blank=True, max_length=254, null=True)),
                ('slug', models.CharField(blank=True, max_length=254, null=True)),
                ('extrait', models.CharField(blank=True, max_length=254, null=True)),
                ('contenu', models.CharField(blank=True, max_length=254, null=True)),
                ('image_couverture', models.CharField(blank=True, max_length=254, null=True)),
                ('statut', models.CharField(blank=True, max_length=254, null=True)),
                ('publie_le', models.DateTimeField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(blank=True, null=True)),
                ('modifie_le', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'articles_blog',
            },
        ),
        migrations.CreateModel(
            name='BandeauMarketing',
            fields=[
                ('bandeau_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('titre', models.CharField(blank=True, max_length=254, null=True)),
                ('image_url', models.CharField(blank=True, max_length=254, null=True)),
                ('lien_url', models.CharField(blank=True, max_length=254, null=True)),
                ('position', models.CharField(blank=True, max_length=254, null=True)),
                ('est_actif', models.BooleanField(blank=True, null=True)),
                ('debut_le', models.DateTimeField(blank=True, null=True)),
                ('fin_le', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bandeaux_marketing',
            },
        ),
        migrations.CreateModel(
            name='Couleur',
            fields=[
                ('couleur_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=254, null=True)),
                ('code_hex', models.CharField(blank=True, max_length=254, null=True)),
                ('slug', models.CharField(blank=True, max_length=254, null=True)),
                ('est_active', models.BooleanField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(blank=True, null=True)),
                ('modifie_le', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'couleurs',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('coupon_id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=254, null=True)),
                ('type', models.CharField(blank=True, max_length=254, null=True)),
                ('premier_achat_uniquement', models.BooleanField(blank=True, null=True)),
                ('canal', models.CharField(blank=True, max_length=254, null=True)),
                ('valeur', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('utilisations_max', models.IntegerField(blank=True, null=True)),
                ('cumulable', models.BooleanField(blank=True, null=True)),
                ('debut_le', models.DateTimeField(blank=True, null=True)),
                ('fin_le', models.DateTimeField(blank=True, null=True)),
                ('montant_min_commande', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('est_actif', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coupons',
            },
        ),
        migrations.CreateModel(
            name='Entrepot',
            fields=[
                ('entrepot_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=254, null=True)),
                ('adresse_json', models.JSONField(blank=True, null=True)),
                ('gps_lat_gps_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('est_actif', models.BooleanField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'entrepots',
            },
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('favoris_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=254, null=True)),
                ('cree_le', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'favoris',
            },
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('livreur_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=254, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=254, null=True)),
                ('type', models.CharField(blank=True, max_length=254, null=True)),
                ('vehicule_type', models.CharField(blank=True, max_length=254, null=True)),
                ('immatriculation', models.CharField(blank=True, max_length=254, null=True)),
                ('zone', models.CharField(blank=True, max_length=254, null=True)),
                ('actif', models.BooleanField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '_livreurs',
            },
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('marque_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=254, null=True)),
                ('slug', models.CharField(blank=True, max_length=254, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=254, null=True)),
                ('site_web_url', models.CharField(blank=True, max_length=254, null=True)),
                ('pays_origine', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.CharField(blank=True, max_length=254, null=True)),
                ('est_active', models.BooleanField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'marques',
            },
        ),
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('remboursement_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('motif', models.CharField(blank=True, max_length=254, null=True)),
                ('statut', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'remboursements',
            },
        ),
        migrations.CreateModel(
            name='Representant',
            fields=[
                ('representant_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=254, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=254, null=True)),
                ('actif', models.BooleanField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'representants',
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('categorie_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=254, null=True)),
                ('slug', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.CharField(blank=True, max_length=254, null=True)),
                ('image_url', models.CharField(blank=True, max_length=254, null=True)),
                ('est_actif', models.BooleanField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(blank=True, null=True)),
                ('bandeau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='christland.bandeaumarketing')),
                ('parent', models.ForeignKey(blank=True, db_column='cat_categorie_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='christland.categorie')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('commande_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('statut', models.CharField(blank=True, max_length=254, null=True)),
                ('statut_paiement', models.CharField(blank=True, max_length=254, null=True)),
                ('statut_livraison', models.CharField(blank=True, max_length=254, null=True)),
                ('sous_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_livraison', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_taxes', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_general', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_remise', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('modifie_le', models.DateTimeField(blank=True, null=True)),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='christland.adresse')),
            ],
            options={
                'db_table': 'commandes',
            },
        ),
        migrations.CreateModel(
            name='AdresseCommande',
            fields=[
                ('adresse_cm_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=254, null=True)),
                ('nom_complet', models.CharField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=254, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('ligne1', models.CharField(blank=True, max_length=254, null=True)),
                ('ligne2', models.CharField(blank=True, max_length=254, null=True)),
                ('ville', models.CharField(blank=True, max_length=254, null=True)),
                ('region', models.CharField(blank=True, max_length=254, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=254, null=True)),
                ('pays', models.CharField(blank=True, max_length=254, null=True)),
                ('notes', models.CharField(blank=True, max_length=254, null=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='christland.commande')),
            ],
            options={
                'db_table': 'adresses_commande',
            },
        ),
        migrations.AddField(
            model_name='bandeaumarketing',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='christland.coupon'),
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('expedition_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mode', models.CharField(blank=True, max_length=254, null=True)),
                ('preuve_signature_url', models.CharField(blank=True, max_length=254, null=True)),
                ('preuve_photo_url', models.CharField(blank=True, max_length=254, null=True)),
                ('numero_suivi', models.IntegerField(blank=True, null=True)),
                ('statut', models.CharField(blank=True, max_length=254, null=True)),
                ('expedie_le', models.DateTimeField(blank=True, null=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='christland.commande')),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='christland.livreur')),
            ],
            options={
                'db_table': 'expeditions',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('produit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=254, null=True)),
                ('slug', models.CharField(blank=True, max_length=254, null=True)),
                ('description_courte', models.CharField(blank=True, max_length=254, null=True)),
                ('description_long', models.CharField(blank=True, max_length=254, null=True)),
                ('garantie_mois', models.IntegerField(blank=True, null=True)),
                ('poids_grammes', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('est_actif', models.BooleanField(blank=True, null=True)),
                ('visible', models.IntegerField(blank=True, null=True)),
                ('pr_avant', models.IntegerField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(blank=True, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=254, null=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='christland.categorie')),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='christland.marque')),
            ],
            options={
                'db_table': 'produits',
            },
        ),
        migrations.CreateModel(
            name='ImageProduit',
            fields=[
                ('image_id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=254, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=254, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('principale', models.CharField(blank=True, max_length=254, null=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='christland.produit')),
            ],
            options={
                'db_table': 'images_produits',
            },
        ),
        migrations.CreateModel(
            name='FavoriClasseur',
            fields=[
                ('element_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ajoute_le', models.DateTimeField(blank=True, null=True)),
                ('favoris', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='christland.favori')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='christland.produit')),
            ],
            options={
                'db_table': 'favoris_classeur',
            },
        ),
        migrations.AddField(
            model_name='bandeaumarketing',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='christland.produit'),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('paiement_id', models.BigAutoField(db_column='paiement_id_pai', primary_key=True, serialize=False)),
                ('fournisseur', models.CharField(blank=True, max_length=254, null=True)),
                ('transaction_externe_id', models.BigIntegerField(blank=True, null=True)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('statut', models.CharField(blank=True, max_length=254, null=True)),
                ('paye_le', models.DateTimeField(blank=True, null=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='christland.commande')),
                ('remboursement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='christland.remboursement')),
            ],
            options={
                'db_table': 'paiements',
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='representant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='christland.representant'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantite_disponible', models.IntegerField(blank=True, null=True)),
                ('quantite_reservee', models.IntegerField(blank=True, null=True)),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='christland.entrepot')),
            ],
            options={
                'db_table': 'stocks',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('utilisateur_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=254, null=True)),
                ('mot_de_passe_hash', models.CharField(blank=True, max_length=254, null=True)),
                ('prenom', models.CharField(blank=True, max_length=254, null=True)),
                ('nom', models.CharField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(blank=True, max_length=254, null=True)),
                ('est_actif', models.BooleanField(blank=True, null=True)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('favoris', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='christland.favori')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='christland.produit')),
            ],
            options={
                'db_table': 'utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('panier_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('montant', models.CharField(blank=True, max_length=254, null=True)),
                ('cree_le', models.DateTimeField(blank=True, null=True)),
                ('session_id', models.BigIntegerField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='christland.utilisateur')),
            ],
            options={
                'db_table': 'paniers',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.BigAutoField(db_column='notification_id_', primary_key=True, serialize=False)),
                ('canal', models.CharField(blank=True, db_column='canal_', max_length=254, null=True)),
                ('modele', models.CharField(blank=True, db_column='modele_', max_length=254, null=True)),
                ('payload_json', models.JSONField(blank=True, db_column='payload_json_', null=True)),
                ('statut', models.CharField(blank=True, db_column='statut_', max_length=254, null=True)),
                ('envoye_le', models.DateTimeField(blank=True, db_column='envoye_le_', null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='christland.utilisateur')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('message_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=254, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=254, null=True)),
                ('canal_prefere', models.CharField(blank=True, max_length=254, null=True)),
                ('statut', models.CharField(blank=True, max_length=254, null=True)),
                ('cree_le', models.DateTimeField(blank=True, null=True)),
                ('sujet', models.CharField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='christland.utilisateur')),
            ],
            options={
                'db_table': 'messages_contact',
            },
        ),
        migrations.CreateModel(
            name='EvenementAnalytics',
            fields=[
                ('evenement_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_evenement', models.CharField(blank=True, max_length=254, null=True)),
                ('date_evenement', models.DateTimeField(blank=True, null=True)),
                ('page_url', models.CharField(blank=True, max_length=254, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=254, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=254, null=True)),
                ('appareil', models.CharField(blank=True, max_length=254, null=True)),
                ('ip', models.CharField(blank=True, max_length=254, null=True)),
                ('pays', models.CharField(blank=True, max_length=254, null=True)),
                ('ville', models.CharField(blank=True, max_length=254, null=True)),
                ('metadonnees_json', models.JSONField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='christland.utilisateur')),
            ],
            options={
                'db_table': 'evenements_analytics',
            },
        ),
        migrations.CreateModel(
            name='CouponUtilisation',
            fields=[
                ('utilisation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('utilise_le', models.DateTimeField(blank=True, null=True)),
                ('montant_remise', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('etat', models.CharField(blank=True, max_length=254, null=True)),
                ('premier_achat', models.BooleanField(blank=True, null=True)),
                ('commission_montant', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('commission_statut', models.CharField(blank=True, max_length=254, null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='christland.coupon')),
                ('representant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='christland.representant')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='christland.utilisateur')),
            ],
            options={
                'db_table': 'coupons_utilisations',
            },
        ),
        migrations.CreateModel(
            name='CommentaireBlog',
            fields=[
                ('commentaire_id', models.IntegerField(primary_key=True, serialize=False)),
                ('contenu', models.CharField(blank=True, max_length=254, null=True)),
                ('statut', models.CharField(blank=True, max_length=254, null=True)),
                ('cree_le', models.DateTimeField(blank=True, null=True)),
                ('approuve_le', models.DateTimeField(blank=True, null=True)),
                ('est_valide', models.BooleanField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='christland.articleblog')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='christland.utilisateur')),
            ],
            options={
                'db_table': 'commentaires_blog',
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='christland.utilisateur'),
        ),
        migrations.CreateModel(
            name='AvisProduit',
            fields=[
                ('avis_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('commentaire', models.CharField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='christland.utilisateur')),
            ],
            options={
                'db_table': 'avis_produits',
            },
        ),
        migrations.AddField(
            model_name='adresse',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='christland.utilisateur'),
        ),
        migrations.CreateModel(
            name='VarianteProduit',
            fields=[
                ('variante_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(blank=True, max_length=254, null=True)),
                ('code_barres', models.CharField(blank=True, max_length=254, null=True)),
                ('nom', models.CharField(blank=True, max_length=254, null=True)),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('prix_compare', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('prix_achat', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('modifie_le', models.DateTimeField(blank=True, null=True)),
                ('is_active_debut_ma', models.BooleanField(blank=True, null=True)),
                ('stock_quantite', models.IntegerField(blank=True, null=True)),
                ('couleur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='christland.couleur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='christland.produit')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='christland.stock')),
            ],
            options={
                'db_table': 'variantes_produits',
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('mouvement_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=254, null=True)),
                ('quantite', models.IntegerField(blank=True, null=True)),
                ('raison', models.CharField(blank=True, max_length=254, null=True)),
                ('cree_le', models.DateTimeField(blank=True, null=True)),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='christland.entrepot')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='christland.varianteproduit')),
            ],
            options={
                'db_table': 'mouvements_stock',
            },
        ),
        migrations.CreateModel(
            name='LignePanier',
            fields=[
                ('variante_id_pa', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantite', models.IntegerField(blank=True, null=True)),
                ('prix_unitaire', models.IntegerField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(blank=True, null=True)),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='christland.panier')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='christland.varianteproduit')),
            ],
            options={
                'db_table': 'lignes_panier',
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('ligne_commande_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_snapshot', models.CharField(blank=True, max_length=254, null=True)),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quantite', models.IntegerField(blank=True, null=True)),
                ('total_ligne', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='christland.commande')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='christland.varianteproduit')),
            ],
            options={
                'db_table': 'lignes_commande',
            },
        ),
        migrations.CreateModel(
            name='Lier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='christland.commande')),
                ('utilisation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='christland.couponutilisation')),
            ],
            options={
                'db_table': 'lier',
                'unique_together': {('utilisation', 'commande')},
            },
        ),
    ]
