# Generated by Django 5.1.2 on 2025-09-25 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('christland', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='livreur',
            table='livreurs',
        ),
    ]
