# Generated by Django 5.1.2 on 2025-09-29 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christland', '0001_initial_20250929'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfants', to='christland.categories'),
        ),
        migrations.AddIndex(
            model_name='categories',
            index=models.Index(fields=['parent'], name='categories_parent__7983b2_idx'),
        ),
    ]
