# Generated by Django 5.1.2 on 2025-10-16 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christland', '0002_categories_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('libelle', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('text', 'Texte'), ('int', 'Entier'), ('dec', 'Décimal'), ('bool', 'Booléen'), ('choice', 'Choix')], default='text', max_length=10)),
                ('unite', models.CharField(blank=True, max_length=20)),
                ('ordre', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'attributs',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='ValeurAttribut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('attribut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valeurs', to='christland.attribut')),
            ],
            options={
                'db_table': 'attributs_valeurs',
                'ordering': ['valeur'],
                'unique_together': {('attribut', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='CategorieAttribut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligatoire', models.BooleanField(default=False)),
                ('ordre', models.IntegerField(default=0)),
                ('attribut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='christland.attribut')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributs', to='christland.categories')),
            ],
            options={
                'db_table': 'categories_attributs',
                'ordering': ['ordre'],
                'unique_together': {('categorie', 'attribut')},
            },
        ),
        migrations.CreateModel(
            name='SpecVariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_text', models.CharField(blank=True, max_length=255)),
                ('valeur_int', models.IntegerField(blank=True, null=True)),
                ('valeur_dec', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('attribut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs_variante', to='christland.attribut')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='christland.variantesproduits')),
                ('valeur_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='christland.valeurattribut')),
            ],
            options={
                'db_table': 'specs_variantes',
                'indexes': [models.Index(fields=['attribut', 'valeur_int'], name='specs_varia_attribu_c6f8d8_idx'), models.Index(fields=['attribut', 'valeur_dec'], name='specs_varia_attribu_69d239_idx'), models.Index(fields=['attribut', 'valeur_choice'], name='specs_varia_attribu_d85206_idx')],
                'unique_together': {('variante', 'attribut')},
            },
        ),
        migrations.CreateModel(
            name='SpecProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_text', models.CharField(blank=True, max_length=255)),
                ('valeur_int', models.IntegerField(blank=True, null=True)),
                ('valeur_dec', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('attribut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs_produit', to='christland.attribut')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='christland.produits')),
                ('valeur_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='christland.valeurattribut')),
            ],
            options={
                'db_table': 'specs_produits',
                'indexes': [models.Index(fields=['attribut', 'valeur_int'], name='specs_produ_attribu_23d2f9_idx'), models.Index(fields=['attribut', 'valeur_dec'], name='specs_produ_attribu_8f8dbf_idx'), models.Index(fields=['attribut', 'valeur_choice'], name='specs_produ_attribu_3eeffa_idx')],
                'unique_together': {('produit', 'attribut')},
            },
        ),
    ]
