# Generated by Django 5.1.2 on 2025-09-25 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('christland', '0002_alter_livreur_table'),
    ]

    operations = [
    ]
