# Generated by Django 5.1.2 on 2025-10-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christland', '0003_attribut_valeurattribut_categorieattribut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produits',
            name='etat',
            field=models.CharField(blank=True, choices=[('neuf', 'Neuf'), ('occasion', 'Occasion'), ('reconditionne', 'Reconditionné')], max_length=20),
        ),
    ]
