# Generated by Django 5.2.7 on 2025-10-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christland', '0004_produits_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specproduit',
            name='valeur_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
