# Generated by Django 5.2.7 on 2025-10-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christland', '0005_alter_specproduit_valeur_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specvariante',
            name='valeur_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
