# Generated by Django 5.2.7 on 2025-10-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christland', '0006_alter_specvariante_valeur_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesblog',
            name='contenu',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='articlesblog',
            name='extrait',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='articlesblog',
            name='slug',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='articlesblog',
            name='titre',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
