# Generated by Django 5.2.7 on 2025-10-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christland', '0007_alter_articlesblog_contenu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesblog',
            name='contenu',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='articlesblog',
            name='extrait',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='articlesblog',
            name='image_couverture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articlesblog',
            name='slug',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='articlesblog',
            name='titre',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='commentairesblog',
            name='contenu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='commentairesblog',
            name='statut',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='commentairesblog',
            name='valide',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
