# Generated by Django 5.2.7 on 2025-10-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christland', '0008_alter_articlesblog_contenu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produits',
            name='quantite',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produits',
            name='etat',
            field=models.CharField(blank=True, choices=[('neuf', 'Neuf'), ('occasion', 'Occasion'), ('reconditionné', 'Reconditionné')], max_length=20),
        ),
    ]
