# Generated by Django 5.1.2 on 2025-10-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christland', '0009_produits_quantite_alter_produits_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantesproduits',
            name='promo_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variantesproduits',
            name='promo_debut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variantesproduits',
            name='promo_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='variantesproduits',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('prix__isnull', False), ('prix_promo__isnull', False), ('promo_active', True), _negated=True), ('prix_promo__lt', models.F('prix')), _connector='OR'), name='promo_inferieure_au_prix_normal_si_active'),
        ),
    ]
