# Generated by Django 5.1.2 on 2025-10-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christland', '0010_variantesproduits_promo_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='cree_le',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='variantesproduits',
            name='cree_le',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
