# Generated by Django 5.1.2 on 2025-10-28 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('christland', '0011_alter_produits_cree_le_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produits',
            name='prix_reference_avant',
        ),
    ]
