# Generated by Django 5.1.2 on 2025-10-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christland', '0012_remove_produits_prix_reference_avant'),
    ]

    operations = [
        migrations.AddField(
            model_name='produits',
            name='commande_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
