# Generated by Django 5.1.2 on 2025-11-06 13:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christland', '0013_produits_commande_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesblog',
            name='publie_le',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.CreateModel(
            name='TranslationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(db_index=True, max_length=80)),
                ('model_name', models.CharField(db_index=True, max_length=120)),
                ('object_id', models.CharField(db_index=True, max_length=64)),
                ('field_name', models.CharField(db_index=True, max_length=120)),
                ('lang', models.CharField(db_index=True, max_length=10)),
                ('text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('app_label', 'model_name', 'object_id', 'field_name', 'lang')},
            },
        ),
    ]
