# Generated by Django 5.1.2 on 2025-11-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christland', '0014_alter_articlesblog_publie_le_translationentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationentry',
            name='source_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
