# Generated by Django 5.1.2 on 2025-11-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christland', '0015_translationentry_source_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=80)),
                ('object_id', models.CharField(max_length=64)),
                ('field', models.CharField(max_length=80)),
                ('lang', models.CharField(max_length=8)),
                ('src_hash', models.CharField(db_index=True, max_length=64)),
                ('value', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done'), ('NOOP', 'Noop'), ('ERROR', 'Error')], default='PENDING', max_length=10)),
                ('provider', models.CharField(blank=True, max_length=40, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['app_label', 'model', 'object_id', 'field', 'lang'], name='christland__app_lab_1af684_idx'), models.Index(fields=['status'], name='christland__status_7e1182_idx')],
                'constraints': [models.UniqueConstraint(fields=('app_label', 'model', 'object_id', 'field', 'lang', 'src_hash'), name='uniq_tr_key_src_hash')],
            },
        ),
    ]
