# Generated by Django 5.1.2 on 2025-11-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christland', '0017_optimize_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='couleurs',
            name='color_slug_idx',
        ),
        migrations.RemoveIndex(
            model_name='imagesproduits',
            name='img_main_idx',
        ),
        migrations.RemoveIndex(
            model_name='marques',
            name='brand_slug_idx',
        ),
        migrations.RemoveIndex(
            model_name='produits',
            name='prod_active_cat',
        ),
        migrations.RemoveIndex(
            model_name='variantesproduits',
            name='var_prix_idx',
        ),
        migrations.RemoveIndex(
            model_name='variantesproduits',
            name='var_promo_idx',
        ),
        migrations.AlterUniqueTogether(
            name='translationentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='translationentry',
            name='source_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produits',
            name='nom',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='translationentry',
            name='source_hash',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='translationentry',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='translationentry',
            unique_together={('app_label', 'model_name', 'object_id', 'field_name', 'lang', 'source_hash')},
        ),
        migrations.AddIndex(
            model_name='translationentry',
            index=models.Index(fields=['app_label', 'model_name', 'object_id', 'field_name', 'lang'], name='christland__app_lab_5dba51_idx'),
        ),
    ]
