# Generated by Django 5.1.2 on 2025-11-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christland', '0018_remove_couleurs_color_slug_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_lang', models.CharField(default='fr', max_length=10)),
                ('target_lang', models.CharField(max_length=10)),
                ('source_text', models.TextField()),
                ('translated_text', models.TextField()),
            ],
            options={
                'unique_together': {('source_lang', 'target_lang', 'source_text')},
            },
        ),
        migrations.DeleteModel(
            name='TranslationEntry',
        ),
    ]
