# Generated by Django 5.1.2 on 2025-11-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christland', '0019_texttranslation_delete_translationentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='variantesproduits',
            name='sku',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
