# Generated by Django 5.1.2 on 2025-11-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christland', '0021_alter_produits_slug_alter_variantesproduits_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantesproduits',
            name='sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
