# Generated by Django 5.2.8 on 2025-12-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christland', '0025_drop_slug_unique_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
