# Generated by Django 5.2.8 on 2025-12-15 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christland', '0028_dashboardactionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardactionlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_actions', to='christland.utilisateurs'),
        ),
    ]
