# Generated by Django 5.2.8 on 2025-12-15 14:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('christland', '0029_alter_dashboardactionlog_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesblog',
            name='image_couverture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='blog'),
        ),
        migrations.AlterField(
            model_name='bandeauxmarketing',
            name='image_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='bandeaux'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='image_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='categories'),
        ),
        migrations.AlterField(
            model_name='imagesproduits',
            name='url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='produits'),
        ),
    ]
