# Generated by Django 5.2.8 on 2025-12-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christland', '0030_alter_articlesblog_image_couverture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesblog',
            name='image_couverture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bandeauxmarketing',
            name='image_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='categories',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imagesproduits',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
