const resources = {
  en: {
    translation: {
        "Accueil": "Home",
        "A propos": "About",
        "Produits": "Products",
        "Services": "Services",
        "Assistance": "Support",
        "Contact": "Contact",
        "Rechercher": "Search",
        "hero.button": "Buy Now",
        "Français": "French",
        "Anglais": "English",
        "highlighted": "technology",
        "hero.title": "Discover the world of modern",
        "hero.description": "Smartphones, computers, headphones, TVs and connected gadgets at the best price.",
        "service.description": "Trust our services: authentic, verified, and responsible brands.",
        "siege": "Head Office",
        "form.button": "Send",
        "name.input": "Name",
        "email.input": "Email",
        "phone.input": "Phone",
        "message.input": "Message",
        "form.description": "Leave your message",
        "bar.description": "Explore All Products",
        "bar.cat": "Categories",
        "com.ach": "PURCHASE PRODUCT",
        "com.nom": "Product",
        "com.type": "Type of Request",
        "com.ex": "EXPLORE OUR MULTIPLE ",
        "com.se": "SERVICES",
        "com.do": "Dual 12 MP camera (wide + ultra-wide), Night Mode, 4K60 video, 12 MP selfie. Face ID, aluminum + glass body, IP68, stereo, Haptic Touch.",
        "com.ref": "Reference",
        "com.qo": "Quote",
        "com.ac": "Purchase",
        "com.in": "Information",
        "com.vo": "VIEW MORE",
        "com.di": "Availability",
        "com.quc": "Quantity",
        "com.np": "Full Name",
        "com.a": "I agree to be contacted",
        "com.sen": "Send via WhatsApp",
        "com.tel": "Phone Number",

    }
  },
  fr: {
    translation: {
        "Accueil": "Accueil",
        "A propos": "A propos",
        "Produits": "Produits",
        "Services": "Services",
        "Assistance": "Assistance",
        "Contact": "Contact",
        "Rechercher": "Rechercher",
        "hero.button": "Acheter Maintenant",
        "Français": "Français",
        "Anglais": "Anglais",
        "highlighted": "technologie",
        "hero.title": "Découvrez l’univers de la",
        "hero.description": "Smartphones, ordinateurs, casques, télévisions et gadgets connectés retrouvez les meilleures marques au meilleur prix.",
        "service.description": "Faites confiance à nos services : des marques authentiques, contrôlées et responsables.",
        "siege": "Siège Principal",
        "form.button": "Envoyer",
        "name.input": "Nom",
        "email.input": "Email",
        "phone.input": "Téléphone",
        "message.input": "Message",
        "bar.description": "Explore Tous Les Produits",
        "bar.cat": "Catégories",
        "com.ach": "ACHAT DE PRODUIT",
        "com.nom": "Produit",
        "com.type": "Type de demande",
        "com.ex": "EXPLORE NOS MULTIPLE",
        "com.se": "SERVICES",
        "com.do": "Double appareil photo 12 MP (grand-angle + ultra grand-angle), Mode Nuit, vidéo 4K60, selfie 12 MP. Face ID, châssis alu + verre, IP68, stéréo, Haptic Touch.",
        "com.ref": "Reference",
        "com.qo": "Devis",
        "com.ac": "Achat",
        "com.in": "Information",
        "com.di": "Disponibilité",
        "com.vo": "VOIR PLUS",
        "com.quc": "Quantité",
        "com.np": "Nom & Prénom",
        "com.a": "J’accepte d’être contacté",
        "com.sen": "Envoyer via Whatsapp",
        "com.tel": "Téléphone",


    }
  }
};

export default resources;