const resources = {
  en: {
    translation: {
        "Accueil": "Home",
        "A propos": "About",
        "A_propos": "About",
        "Produits": "Products",
        "Services": "Services",
        "Assistance": "Support",
        "Contact": "Contact",
        "Rechercher": "Search",
        "hero.button": "Buy Now",
        "Français": "French",
        "Anglais": "English",
        "highlighted": "technology",
        "highlighted1": "It's simple",
        "highlighted2": "We want what you want.",
        "hero.title": "Discover the world of modern",
        "about.title": "We Are an Independent Provider of Technology and Services.",
        "about.description": "We are a responsible company that believes in the possibility of succeeding together for our employees and our planet. We support our clients through the phases of procurement, transformation, and management of their technological infrastructure to ensure a digital transformation that enables their employees and their business to grow.",
        "hero.description": "Smartphones, computers, headphones, TVs and connected gadgets at the best price.",
        "service.description": "Trust our services: authentic, verified, and responsible brands.",
        "siege": "Head Office",
        "form.button": "Send",
        "service.button": "Our Services",
        "form.button1": "Sign Up",
        "form.button2": "Sign In",
        "name.input": "Name",
        "email.input": "Email",
        "phone.input": "Phone",
        "message.input": "Message",
        "password.input": "Password",
        "confirm.input": "Password confirm",
        "form.description": "Leave your message",
        "compte.desc": "Already have an account ?",
        "compte.desc1": "Log In",
        "compte.desc2": "Not registreted ?",
        "compte.desc3": "Sign Up",
        "team": "Our Team",
        "categorie": "OUR CATEGORIES",
        "team.des": "We focus on the details of everything we do to help businesses around the world focus on what matters most to them.",
        "team.contact": "Contact Us",
        "stat.client": "Satisfied Clients",
        "stat.exp":  "Experience",
        "stat.commande": "Commands",
    }
  },
  fr: {
    translation: {
        "Accueil": "Accueil",
        "A propos": "A propos",
        "A_propos": "A propos de",
        "Produits": "Produits",
        "Services": "Services",
        "Assistance": "Assistance",
        "Contact": "Contact",
        "Rechercher": "Rechercher",
        "hero.button": "Acheter Maintenant",
        "Français": "Français",
        "Anglais": "Anglais",
        "highlighted": "technologie",
        "highlighted1": "C'est simple",
        "highlighted2": "Nous voulons ce que vous voulez.",
        "hero.title": "Découvrez l’univers de la",
        "about.title": "Nous Sommes Un Fournisseur Indépendant De Technologies Et De Services.",
        "about.description": "Nous sommes une entreprise responsable qui croit en la possibilité de gagner ensemble pour nos collaborateurs et notre planète, continent. Nous accompagnons nos clients dans les phases d'approvisionnement, de transformation et de gestion de leur infrastructure technologique pour leur assurer une transformation numérique permettant à leurs employés et à leur entreprise de se développer.",
        "hero.description": "Smartphones, ordinateurs, casques, télévisions et gadgets connectés retrouvez les meilleures marques au meilleur prix.",
        "service.description": "Faites confiance à nos services : des marques authentiques, contrôlées et responsables.",
        "siege": "Siège Principal",
        "service.button": "Nos Services",
        "form.button": "Envoyer",
        "form.button1": "Créer Compte",
        "form.button2": "Connexion",
        "name.input": "Nom",
        "email.input": "Email",
        "phone.input": "Téléphone",
        "message.input": "Message",
        "password.input": "Mot de passe",
        "confirm.input": "Confirmation mot de passe",
        "form.description": "Laissez votre message",
        "compte.desc": "Déjà un compte ?",
        "compte.desc1": "Connectez-vous",
        "compte.desc2": "Pas encore enregistré ?",
        "compte.desc3": "Créez votre compte",
        "team": "Notre Equipe",
        "categorie": "NOS CATEGORIES",
        "team.des": "Nous nous concentrons sur les détails de tout ce que nous faisons, afin d’aider les entreprises du monde entier à se focaliser sur ce qui compte le plus pour elles.",
        "team.contact": "Nous Contacter",
        "stat.client": "Clients Satisfaits",
        "stat.exp":  "Expérience",
        "stat.commande": "Commandes",
    }
  }
};

export default resources;