const resources = {
  en: {
    translation: {
        "Accueil": "Home",
        "A propos": "About",
        "Produits": "Products",
        "Services": "Services",
        "Assistance": "Support",
        "Contact": "Contact",
        "Rechercher": "Search",
        "hero.button": "Buy Now",
        "Français": "French",
        "Anglais": "English",
        "highlighted": "technology",
        "hero.title": "Discover the world of modern",
        "hero.description": "Smartphones, computers, headphones, TVs and connected gadgets at the best price.",
        "service.description": "Trust our services: authentic, verified, and responsible brands.",
        "siege": "Head Office",
        "form.button": "Send",
        "form.button1": "Sign Up",
        "form.button2": "Sign In",
        "name.input": "Name",
        "email.input": "Email",
        "phone.input": "Phone",
        "message.input": "Message",
        "password.input": "Password",
        "confirm.input": "Password confirm",
        "form.description": "Leave your message",
        "compte.desc": "Already have an account ?",
        "compte.desc1": "Log In",
        "compte.desc2": "Not registreted ?",
        "compte.desc3": "Sign Up",
    }
  },
  fr: {
    translation: {
        "Accueil": "Accueil",
        "A propos": "A propos",
        "Produits": "Produits",
        "Services": "Services",
        "Assistance": "Assistance",
        "Contact": "Contact",
        "Rechercher": "Rechercher",
        "hero.button": "Acheter Maintenant",
        "Français": "Français",
        "Anglais": "Anglais",
        "highlighted": "technologie",
        "hero.title": "Découvrez l’univers de la",
        "hero.description": "Smartphones, ordinateurs, casques, télévisions et gadgets connectés retrouvez les meilleures marques au meilleur prix.",
        "service.description": "Faites confiance à nos services : des marques authentiques, contrôlées et responsables.",
        "siege": "Siège Principal",
        "form.button": "Envoyer",
        "form.button1": "Créer Compte",
        "form.button2": "Connexion",
        "name.input": "Nom",
        "email.input": "Email",
        "phone.input": "Téléphone",
        "message.input": "Message",
        "password.input": "Mot de passe",
        "confirm.input": "Confirmation mot de passe",
        "form.description": "Laissez votre message",
        "compte.desc": "Déjà un compte ?",
        "compte.desc1": "Connectez-vous",
        "compte.desc2": "Pas encore enregistré ?",
        "compte.desc3": "Créez votre compte",
    }
  }
};

export default resources;